name: proyecto
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^8.0.1
  http: ^0.13.4
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  weather_icons: ^3.0.0
  flutter_spinkit: ^5.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.0.8
  geolocator: ^8.0.1
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
